version: 2
jobs:
   build:
     docker:
       - image: danteev/texlive
     steps:
       - checkout
       - run: pushd Pflichtenheft && latexmk -pdf Lastenheft.tex && popd && pushd Entwurf && latexmk -pdf Entwurf.tex && popd